/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrackRouteImport } from './routes/app.track'
import { Route as AppStoresRouteImport } from './routes/app.stores'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppServiceTypeRouteImport } from './routes/app.service.$type'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceTypeRoute = AppServiceTypeRouteImport.update({
  id: '/service/$type',
  path: '/service/$type',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stores': typeof AppStoresRoute
  '/app/track': typeof AppTrackRoute
  '/app/': typeof AppIndexRoute
  '/app/service/$type': typeof AppServiceTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stores': typeof AppStoresRoute
  '/app/track': typeof AppTrackRoute
  '/app': typeof AppIndexRoute
  '/app/service/$type': typeof AppServiceTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stores': typeof AppStoresRoute
  '/app/track': typeof AppTrackRoute
  '/app/': typeof AppIndexRoute
  '/app/service/$type': typeof AppServiceTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/profile'
    | '/app/stores'
    | '/app/track'
    | '/app/'
    | '/app/service/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/orders'
    | '/app/profile'
    | '/app/stores'
    | '/app/track'
    | '/app'
    | '/app/service/$type'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/profile'
    | '/app/stores'
    | '/app/track'
    | '/app/'
    | '/app/service/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/track': {
      id: '/app/track'
      path: '/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stores': {
      id: '/app/stores'
      path: '/stores'
      fullPath: '/app/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service/$type': {
      id: '/app/service/$type'
      path: '/service/$type'
      fullPath: '/app/service/$type'
      preLoaderRoute: typeof AppServiceTypeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStoresRoute: typeof AppStoresRoute
  AppTrackRoute: typeof AppTrackRoute
  AppIndexRoute: typeof AppIndexRoute
  AppServiceTypeRoute: typeof AppServiceTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppStoresRoute: AppStoresRoute,
  AppTrackRoute: AppTrackRoute,
  AppIndexRoute: AppIndexRoute,
  AppServiceTypeRoute: AppServiceTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
